### ISSUE TITLE
Conda-Forge Package

### ISSUE THREAD

**Issue by Zeitsperre** [rsokl/custom_inherit#26]
I'm curious if you would be interested in making this package available on Anaconda distributions via Conda-Forge. Seeing as this package has no dependencies, packaging it there would be a breeze, allowing for users to leverage it within Anaconda/Miniconda environments without relying on `pip`.

I can guide you through the process if this helps.

**Comment by Zeitsperre** [comment]
I can't speak to how it used to be (I only started with Anaconda in the past two years) but the process is realy simple now: https://conda-forge.org/#add_recipe

If you want to fork their [staged-recipes](https://github.com/conda-forge/staged-recipes) repo, I can very quickly draft a recipe as a PR. So long as the dependencies remain simple, maintenance is as easy as opening a PR and updating two lines for each release.

**Comment by rsokl** [comment]
In progress: https://github.com/conda-forge/staged-recipes/pull/9799
