### ISSUE TITLE
Allow docstring of __init__ to also inherit from the parent class

### ISSUE THREAD

**Issue by Boubsi** [rsokl/custom_inherit#30]
Hi all,

I noticed that, all methods starting and ending by "__" was kept off the docstring inheritance when the metaclass `DocInheritMeta` is used. 

What is the reason for that? I would like the `__init__` docstring also inherit from the parent class, could we imagine to have that as an option? is there any reason we should not always include it in the inheritance process?

**Comment by rsokl** [comment]
I think that this was a poorly-informed design choice on my end from long ago. I would be certainly be willing to add it as an option – `include_special_methods` – in `DocInheritMeta`. I am not sure when I would be able to get around to it, but I would happily approve a PR :)

**Comment by rsokl** [comment]
Closed by #31
