### ISSUE TITLE
Inherit docstrings from Zope Interfaces

### ISSUE THREAD

**Issue by mforbes** [rsokl/custom_inherit#32]
Feature request: inherit docstrings from `zope.interface`.  For example:

```python
from custom_inherit import DocInheritMeta
from zope.interface import implementer, Interface

class IClass(Interface):
    x = Attribute("Variable x.  Insert this description to class documentation.")
    def __init__(x):
        """Constructor.  Sets `x`"""
    def power(p):
        """Return `x**p`"""

@implementer(IClass)
class Class(metadata=DocInheritMeta(style="numpy")):
    def __init__(self, x):
        self.x = x
    def power(self, p):
        return self.x**p

c = Class(x=5)
```

Not sure if anything else is needed from an interface perspective: I think `DocInheritMeta` can probably just check to see if `Class` has the appropriate attributes (set by the `implementer` decorator) and then extract the documentation using duck typing.

If you think this fits with the design of `custom_inherit`, I can look at submitting a PR.

**Comment by rsokl** [comment]
Hi @mforbes , thanks for taking the time to write this up. I am interested in supporting `zope.interface`, as long as the implementation is conservative.

Could you indicate the attributes that we would need to look for to support this? If these are sufficiently obscure (i.e. we don't run the risk of false-positives when looking for a zope interface), then I would be happy to review a PR for this.

**Comment by rsokl** [comment]
Closing this until I hear back
